# Superuser for docker commands and such
sudo: required

# python environment and python version
language: python
python: 
  - "3.6"

# What sources to auto build
branches:
  only:
  - master
  - develop
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

matrix:
  include:
    - name: "Test 1"
      env: EXTRACTOR_BRANCH=opendronemap
      env: TEST_STRING=Test1String
    - name: "Test 2"
      env: EXTRACTOR_BRANCH=clipbyshape
      env: TEST_STRING=Test2String
    - name: "Test 3"
      env: EXTRACTOR_BRANCH=canopycover
      env: TEST_STRING=Test3String

env:
  global:
    - FOO=bar

before_install:
  - echo "Before install:\ $TEST_STRING""

install:
  - echo "Install step

script:
  - echo "${EXTRACTOR_BRANCH}"
  - echo "${FOO}"
  - ./app.py "${EXTRACTOR_BRANCH}" "${FOO}"
  - ./other.py "${EXTRACTOR_BRANCH}"